[global]
developmentMode = false

[server]
port = 8501

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = false

[runner]
fastReruns = true

[pages]
  [pages."11_simple_api_client.py"]
    title = "Simple API Client"
    icon = "ğŸ§ª"
  [pages."12_config_api_client.py"]
    title = "API Server Control"
    icon = "âš™ï¸"
  [pages."21_logs_viewer.py"]
    title = "Logs Viewer"
    icon = "îœ"
